### ISSUE TITLE
pytorch setup

### ISSUE THREAD

**Issue by xiaoyanLi629** [viash-io/viash_web#86]
Hello,

I am wondering whether you could provide an example for how to create a docker with pytorch package in the yaml file. I spent too much time on this and still couldn't figure it out.

Thank you!

**Comment by rcannood** [comment]
Hello @xiaoyanLi629 !

Could you provide me with some reproducible code of what you're trying to do and what the error message you're getting is?

Do the following examples solve the problem that you're having?

Kind regards,
Robrecht



### Example 1: installing pytorch on top of a base python image
If you want a docker image with the pytorch package in the yaml file, you could simply do something like:

```yaml
functionality:
  name: test
  resources:
    - type: python_script
      dest: script.py
      text: |
        import torch
        print("Torch version: " + torch.__version__)
platforms:
  - type: docker
    image: python:3.8
    setup:
      - type: python
        packages: 
          - torch
          - numpy
```

You can run the component to see that it works:
```bash
$ viash run config.vsh.yaml
Torch version: 1.9.1+cu102
```

If you change something to the config, the container won't automatically be rebuilt. To do this, you need to run:
```bash
$ viash run config.vsh.yaml -- ---setup cachedbuild
[notice] Running 'docker build -t test:latest /tmp/viashsetupdocker-test-GWByid'
```

### Example 2: Using pre-built pytorch container
Building the container from scratch takes a while. Rather than starting from a base python container, you might want to simply use the pytorch container instead:

```yaml
functionality:
  name: test
  resources:
    - type: python_script
      dest: script.py
      text: |
        import torch
        print("Torch version: " + torch.__version__)
platforms:
  - type: docker
    image: "pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime"
```

As long as the base image has bash installed, this should work just as well:

```bash
$ viash run config.vsh.yaml -- ---setup cachedbuild
[notice] Running 'docker build -t test:latest /tmp/viashsetupdocker-test-3KmsRR'
$ viash run config.vsh.yaml
Torch version: 1.9.0
```
